export enum CARD_DESIGN_TYPES{
  ONLY_BODY,
  ONLY_HEADER_BODY,
  ONLY_BODY_FOOTER,
  FULL_PLAIN_CARD,
  CARD_WITH_IMAGE,
  CARD_WITH_LINK
}

export enum CACHE_TYPES{
  TEMPORARY,
  PERMANENT
}
export enum CACHE_KEY_NAMES{
  USER_CONFIG = 'USER_CONFIG'
}
